Ut1 file
robertoalonsojimenez/aad pull request #1
Opened 2021-10-22 16:15 UTC by robertoalonsojimenez

Terminado funcionamiento completo UT-01

2021-11-08 11:19 UTC, JavierManc commented on app/src/main/java/com/ralonsojim/add_playground/MainActivity.kt
> +    private lateinit var buttonSave: AppCompatButton
El nombre de la variable está bien, pero para los botones es mejor que pongas action... , por ejemplo actionSave.

2021-11-08 11:36 UTC, JavierManc requested changes
He propuesto algún cambio, revísalos :)

2021-11-08 11:36 UTC, JavierManc commented on app/src/main/java/com/ralonsojim/add_playground/ut_01/FilePlayGround.kt
>  class FilePlayGround (private val activity: AppCompatActivity){
¿Por qué esta clase no hace nada?.

2021-11-08 11:36 UTC, JavierManc commented on app/src/main/java/com/ralonsojim/add_playground/MainActivity.kt
> +    private fun saveFile(){
Este método podría ir en una clase externa para así dejar más libre el Main, por ejemplo en una clase llamada ManageFiles.

2021-11-08 11:36 UTC, JavierManc commented on app/src/main/java/com/ralonsojim/add_playground/MainActivity.kt
> +    private fun showFileContent(){
Este método podría ir en una clase externa para así dejar más libre el Main, por ejemplo en una clase llamada ManageFiles.

2021-11-08 11:36 UTC, JavierManc commented on app/src/main/java/com/ralonsojim/add_playground/MainActivity.kt
> +    private fun showExplorer() {
Este método podría ir en una clase externa para así dejar más libre el Main, por ejemplo en una clase llamada ManageFiles.

2021-11-08 11:36 UTC, JavierManc commented on app/src/main/java/com/ralonsojim/add_playground/MainActivity.kt
> +    private fun deleteFile(){
Este método podría ir en una clase externa para así dejar más libre el Main, por ejemplo en una clase llamada ManageFiles.

2021-11-08 11:36 UTC, JavierManc commented on app/src/main/java/com/ralonsojim/add_playground/MainActivity.kt
> +    private fun clearInputs() {
Este método podría ir en una clase externa para así dejar más libre el Main, por ejemplo en una clase llamada ManageFiles.

2021-11-08 11:36 UTC, JavierManc commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="125dp" />
Este tamaño es demasiado grande, ¿no hay otra manera para poder hacerlo?.
Además, todos los tamaños se pueden agrupar en una clase llamada "dimen" dentro de la carpeta "values".

2021-11-11 15:42 UTC, jmperezra approved these changes
@robertoalonsojimenez : hay código muy acoplado, es decir, la actividad que tiene como única responsabilidad pintar elementos en la UI tu tienes métodos para crear y recuperar ficheros. La actividad tiene al menos, dos responsabilidad: UI y trabajar con ficheros. Sólo debería tener una.
@JavierManc: cuando decimos que hay algo que mejorar, hay que indicar cual es tu 'propuesta' (proposal) y el por qué. Si hay un valor 120dp y le indicamos que lo meta en dimens, debemos explicar por qué viene bien tener estos valores en un único fichero y no valores fijos por todo el proyecto. Por lo demás, está genial.

2021-11-11 15:42 UTC, jmperezra commented on app/src/main/java/com/ralonsojim/add_playground/MainActivity.kt
> +    private lateinit var buttonSave: AppCompatButton
Quizás deberíamos evitar añadir una palabra que ya se sabe lo que es, es decir, si ya sabemos que es un button no hace falta añadirlo al nombre de la variable. Una propuesta sería la que indica @JavierManc , actionSave

2021-11-11 15:42 UTC, jmperezra commented on app/src/main/java/com/ralonsojim/add_playground/MainActivity.kt
> +        textFileContent = findViewById(R.id.text_file_content)
Lo mismo que ha pasado con el botón, si lo que mostramos es un texto sin más, quizás labelFileContent encaje más.

2021-11-11 15:42 UTC, jmperezra commented on app/src/main/java/com/ralonsojim/add_playground/MainActivity.kt
> +    private fun saveFile(){
Como dice Javier, quizás la Activity no tiene la responsabilidad de guardar ficheros, sino mostrar información en la UI. Habría que intentar modelar estas acciones.

2021-11-11 15:42 UTC, jmperezra commented on app/src/main/java/com/ralonsojim/add_playground/ut_01/FilePlayGround.kt
>  class FilePlayGround (private val activity: AppCompatActivity){
Quizás esta clase es la que debería contener todos los métodos relacionados con Ficheros.
Pista: alta cohesion y bajo acoplamiento.

2021-11-11 15:42 UTC, jmperezra commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="125dp" />
Según el naming del id, deduzco que este textview muestra un listado de ficheros. Quizás deberíamos poner un wrap-content para que se adapte al número de ficheros que tenemos. Si quieres una altura mínima, existe un atributo para ello: min-height.

2021-11-16 18:23 UTC, closed without merging